GET http://localhost:3000/players/
###

POST http://localhost:3000/players/12/
Content-Type: application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 17,
  "role": "Bowler"
}
###


PUT http://localhost:3000/players/7/


{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}

###
GET http://localhost:3000/players/7/
###



DELETE http://localhost:3000/players/5/


###

GET http://localhost:3000/players/
###

